# To use, configure github repo settings -> Secrets:
#   * DOCKER_REGISTRY   eg. docker.io:port/ (optional, leave unset for dockerhub, trailing slash REQUIRED)
#   * DOCKER_ORGANIZATION
#   * DOCKER_USERNAME
#   * DOCKER_PASSWORD
#   * GIT_REPO


name: Build Docker Node
on: [push, pull_request, workflow_dispatch]

jobs:
  job0:
    name: Build Docker Node
    runs-on: ubuntu-20.04
    steps:
      - name: Determine Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_REGISTRY }}${{ secrets.DOCKER_ORGANIZATION }}/node
          tags: |
            type=sha,format=long,prefix=
            type=ref,event=tag
            type=ref,event=branch
            type=ref,event=pr
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: example/deployment/docker/node
          build-args: |
            GIT_REPO=${{ secrets.GIT_REPO }}
            GIT_REF=${{ github.sha }}
          tags: ${{ steps.meta.outputs.tags }}
